# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'TravelApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelApp

  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'GoogleMaps'
  pod 'GooglePlacesSearchController'
  pod 'GooglePlaces'
  pod 'SwiftyJSON', :git =>'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'RNCryptor', '~> 5.0'
  pod 'CryptoSwift'

  target 'TravelAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TravelAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
